networks:
  databases:
    internal: true

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - databases

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - databases

  scholasix:
    build: .
    restart: unless-stopped
    networks:
      - databases
