networks:
  databases:
    internal: true

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - databases

  scholasix:
    build: .
    restart: unless-stopped
    networks:
      - databases
